# Site settings
title: "Benjamin Yoon's Portfolio"
email: yoonb2002@gmail.com
description: "Benjamin Yoon's professional portfolio, showcasing full-stack development, machine learning projects, and more."
baseurl: "/portfolio"
url: "https://yoonbenjamin.github.io/"

# Social media links
twitter_username: your_twitter_handle
github_username: yoonbenjamin

# Navigation links
header:
  nav:
    - title: "Home"
      url: "/"
    - title: "Portfolio"
      url: "/portfolio/"
    - title: "About"
      url: "/about/"
    - title: "Contact"
      url: "/contact/"
    - title: "Blog"
      url: "/blog/"

# Build settings
# theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-feed
  - github-pages
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache  

footer:
links:
  - title: "GitHub"
    url: "https://github.com/yoonbenjamin"
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/benyoon/"
