# Site settings
title: "Benjamin Yoon's Portfolio"
email: yoonb2002@gmail.com
description: "Benjamin Yoon's professional portfolio, showcasing full-stack development, machine learning projects, and more."
baseurl: ""
url: "https://github.com/yoonbenjamin.github.io"

# Social media links
twitter_username: your_twitter_handle
github_username: yoonbenjamin

# Navigation links
header:
  nav:
    - title: "Home"
      url: "/"
    - title: "Portfolio"
      url: "/portfolio/"
    - title: "About"
      url: "/about/"
    - title: "Contact"
      url: "/contact/"
    - title: "Blog"
      url: "/blog/"

# Build settings
# theme: "minimal-mistakes-jekyll"
theme                    : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed

footer:
links:
  - title: "GitHub"
    url: "https://github.com/yoonbenjamin"
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/benyoon/"

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
