# Theme Settings
minimal_mistakes_skin: "default"

# Site Settings
locale: "en-US"
title: "Portfolio"
title_separator: "-"
name: "Benjamin Yoon"
description: "A Software Developer passionate about full-stack development and machine learning."
url: "https://yoonbenjamin.github.io" # Update this after deploying to GitHub Pages
baseurl: "" # leave empty since the site will be hosted on GitHub Pages
repository: "yoonbenjamin/portfolio" # Your GitHub repo name

# SEO and Social Sharing
og_image: "/assets/images/og-image.jpg" # Add your Open Graph image for better social sharing
social:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yoonbenjamin"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/benyoon"

# Site Author
author:
  name: "Benjamin Yoon"
  avatar: "/assets/images/bio-photo.jpg" # Add a professional image
  bio: "I'm a Software Developer with experience in full-stack development, machine learning, and cloud computing."
  location: "Philadelphia, PA"
  email: "yoonb2002@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yoonbenjamin"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/benyoon"

# Pagination with jekyll-paginate
paginate: 5
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:title/
timezone: America/New_York

# Include `_pages` directory so Jekyll can detect your custom pages
include:
  - _pages

# Default settings for posts and pages
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "single"
      author_profile: true
